/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TesterRouteImport } from './routes/tester'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SellerSolutionsRouteImport } from './routes/seller-solutions'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as ForSellersRouteImport } from './routes/for-sellers'
import { Route as ForBuyersRouteImport } from './routes/for-buyers'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as GiftCardsIndexRouteImport } from './routes/gift-cards.index'
import { Route as NewsMarket360TestersProgramRouteImport } from './routes/news.market360-testers-program'
import { Route as NewsMarket360GiftCardsLaunchRouteImport } from './routes/news.market360-gift-cards-launch'
import { Route as NewsMarket360GiftCardCollectionRouteImport } from './routes/news.market360-gift-card-collection'
import { Route as NewsMarket360AndroidAppLiveRouteImport } from './routes/news.market360-android-app-live'
import { Route as GiftCardsSilverRouteImport } from './routes/gift-cards.silver'
import { Route as GiftCardsPlatinumRouteImport } from './routes/gift-cards.platinum'
import { Route as GiftCardsM360SuperRouteImport } from './routes/gift-cards.m360-super'
import { Route as GiftCardsGoldRouteImport } from './routes/gift-cards.gold'
import { Route as GiftCardsDiamondRouteImport } from './routes/gift-cards.diamond'
import { Route as GiftCardsBronzeRouteImport } from './routes/gift-cards.bronze'
import { Route as ApiPublicInvestorInterestRouteImport } from './routes/api/public/investor-interest'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TesterRoute = TesterRouteImport.update({
  id: '/tester',
  path: '/tester',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSolutionsRoute = SellerSolutionsRouteImport.update({
  id: '/seller-solutions',
  path: '/seller-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSellersRoute = ForSellersRouteImport.update({
  id: '/for-sellers',
  path: '/for-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBuyersRoute = ForBuyersRouteImport.update({
  id: '/for-buyers',
  path: '/for-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsIndexRoute = GiftCardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GiftCardsRoute,
} as any)
const NewsMarket360TestersProgramRoute =
  NewsMarket360TestersProgramRouteImport.update({
    id: '/news/market360-testers-program',
    path: '/news/market360-testers-program',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsMarket360GiftCardsLaunchRoute =
  NewsMarket360GiftCardsLaunchRouteImport.update({
    id: '/news/market360-gift-cards-launch',
    path: '/news/market360-gift-cards-launch',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsMarket360GiftCardCollectionRoute =
  NewsMarket360GiftCardCollectionRouteImport.update({
    id: '/news/market360-gift-card-collection',
    path: '/news/market360-gift-card-collection',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsMarket360AndroidAppLiveRoute =
  NewsMarket360AndroidAppLiveRouteImport.update({
    id: '/news/market360-android-app-live',
    path: '/news/market360-android-app-live',
    getParentRoute: () => rootRouteImport,
  } as any)
const GiftCardsSilverRoute = GiftCardsSilverRouteImport.update({
  id: '/silver',
  path: '/silver',
  getParentRoute: () => GiftCardsRoute,
} as any)
const GiftCardsPlatinumRoute = GiftCardsPlatinumRouteImport.update({
  id: '/platinum',
  path: '/platinum',
  getParentRoute: () => GiftCardsRoute,
} as any)
const GiftCardsM360SuperRoute = GiftCardsM360SuperRouteImport.update({
  id: '/m360-super',
  path: '/m360-super',
  getParentRoute: () => GiftCardsRoute,
} as any)
const GiftCardsGoldRoute = GiftCardsGoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => GiftCardsRoute,
} as any)
const GiftCardsDiamondRoute = GiftCardsDiamondRouteImport.update({
  id: '/diamond',
  path: '/diamond',
  getParentRoute: () => GiftCardsRoute,
} as any)
const GiftCardsBronzeRoute = GiftCardsBronzeRouteImport.update({
  id: '/bronze',
  path: '/bronze',
  getParentRoute: () => GiftCardsRoute,
} as any)
const ApiPublicInvestorInterestRoute =
  ApiPublicInvestorInterestRouteImport.update({
    id: '/api/public/investor-interest',
    path: '/api/public/investor-interest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/gift-cards': typeof GiftCardsRouteWithChildren
  '/help': typeof HelpRoute
  '/investments': typeof InvestmentsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/seller-solutions': typeof SellerSolutionsRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tester': typeof TesterRoute
  '/wallet': typeof WalletRoute
  '/gift-cards/bronze': typeof GiftCardsBronzeRoute
  '/gift-cards/diamond': typeof GiftCardsDiamondRoute
  '/gift-cards/gold': typeof GiftCardsGoldRoute
  '/gift-cards/m360-super': typeof GiftCardsM360SuperRoute
  '/gift-cards/platinum': typeof GiftCardsPlatinumRoute
  '/gift-cards/silver': typeof GiftCardsSilverRoute
  '/news/market360-android-app-live': typeof NewsMarket360AndroidAppLiveRoute
  '/news/market360-gift-card-collection': typeof NewsMarket360GiftCardCollectionRoute
  '/news/market360-gift-cards-launch': typeof NewsMarket360GiftCardsLaunchRoute
  '/news/market360-testers-program': typeof NewsMarket360TestersProgramRoute
  '/gift-cards/': typeof GiftCardsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/investor-interest': typeof ApiPublicInvestorInterestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/help': typeof HelpRoute
  '/investments': typeof InvestmentsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/seller-solutions': typeof SellerSolutionsRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tester': typeof TesterRoute
  '/wallet': typeof WalletRoute
  '/gift-cards/bronze': typeof GiftCardsBronzeRoute
  '/gift-cards/diamond': typeof GiftCardsDiamondRoute
  '/gift-cards/gold': typeof GiftCardsGoldRoute
  '/gift-cards/m360-super': typeof GiftCardsM360SuperRoute
  '/gift-cards/platinum': typeof GiftCardsPlatinumRoute
  '/gift-cards/silver': typeof GiftCardsSilverRoute
  '/news/market360-android-app-live': typeof NewsMarket360AndroidAppLiveRoute
  '/news/market360-gift-card-collection': typeof NewsMarket360GiftCardCollectionRoute
  '/news/market360-gift-cards-launch': typeof NewsMarket360GiftCardsLaunchRoute
  '/news/market360-testers-program': typeof NewsMarket360TestersProgramRoute
  '/gift-cards': typeof GiftCardsIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/public/investor-interest': typeof ApiPublicInvestorInterestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/gift-cards': typeof GiftCardsRouteWithChildren
  '/help': typeof HelpRoute
  '/investments': typeof InvestmentsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/seller-solutions': typeof SellerSolutionsRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tester': typeof TesterRoute
  '/wallet': typeof WalletRoute
  '/gift-cards/bronze': typeof GiftCardsBronzeRoute
  '/gift-cards/diamond': typeof GiftCardsDiamondRoute
  '/gift-cards/gold': typeof GiftCardsGoldRoute
  '/gift-cards/m360-super': typeof GiftCardsM360SuperRoute
  '/gift-cards/platinum': typeof GiftCardsPlatinumRoute
  '/gift-cards/silver': typeof GiftCardsSilverRoute
  '/news/market360-android-app-live': typeof NewsMarket360AndroidAppLiveRoute
  '/news/market360-gift-card-collection': typeof NewsMarket360GiftCardCollectionRoute
  '/news/market360-gift-cards-launch': typeof NewsMarket360GiftCardsLaunchRoute
  '/news/market360-testers-program': typeof NewsMarket360TestersProgramRoute
  '/gift-cards/': typeof GiftCardsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/investor-interest': typeof ApiPublicInvestorInterestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-buyers'
    | '/for-sellers'
    | '/gift-cards'
    | '/help'
    | '/investments'
    | '/privacy'
    | '/safety'
    | '/seller-solutions'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tester'
    | '/wallet'
    | '/gift-cards/bronze'
    | '/gift-cards/diamond'
    | '/gift-cards/gold'
    | '/gift-cards/m360-super'
    | '/gift-cards/platinum'
    | '/gift-cards/silver'
    | '/news/market360-android-app-live'
    | '/news/market360-gift-card-collection'
    | '/news/market360-gift-cards-launch'
    | '/news/market360-testers-program'
    | '/gift-cards/'
    | '/news/'
    | '/api/public/investor-interest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-buyers'
    | '/for-sellers'
    | '/help'
    | '/investments'
    | '/privacy'
    | '/safety'
    | '/seller-solutions'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tester'
    | '/wallet'
    | '/gift-cards/bronze'
    | '/gift-cards/diamond'
    | '/gift-cards/gold'
    | '/gift-cards/m360-super'
    | '/gift-cards/platinum'
    | '/gift-cards/silver'
    | '/news/market360-android-app-live'
    | '/news/market360-gift-card-collection'
    | '/news/market360-gift-cards-launch'
    | '/news/market360-testers-program'
    | '/gift-cards'
    | '/news'
    | '/api/public/investor-interest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-buyers'
    | '/for-sellers'
    | '/gift-cards'
    | '/help'
    | '/investments'
    | '/privacy'
    | '/safety'
    | '/seller-solutions'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tester'
    | '/wallet'
    | '/gift-cards/bronze'
    | '/gift-cards/diamond'
    | '/gift-cards/gold'
    | '/gift-cards/m360-super'
    | '/gift-cards/platinum'
    | '/gift-cards/silver'
    | '/news/market360-android-app-live'
    | '/news/market360-gift-card-collection'
    | '/news/market360-gift-cards-launch'
    | '/news/market360-testers-program'
    | '/gift-cards/'
    | '/news/'
    | '/api/public/investor-interest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  ForBuyersRoute: typeof ForBuyersRoute
  ForSellersRoute: typeof ForSellersRoute
  GiftCardsRoute: typeof GiftCardsRouteWithChildren
  HelpRoute: typeof HelpRoute
  InvestmentsRoute: typeof InvestmentsRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SellerSolutionsRoute: typeof SellerSolutionsRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TesterRoute: typeof TesterRoute
  WalletRoute: typeof WalletRoute
  NewsMarket360AndroidAppLiveRoute: typeof NewsMarket360AndroidAppLiveRoute
  NewsMarket360GiftCardCollectionRoute: typeof NewsMarket360GiftCardCollectionRoute
  NewsMarket360GiftCardsLaunchRoute: typeof NewsMarket360GiftCardsLaunchRoute
  NewsMarket360TestersProgramRoute: typeof NewsMarket360TestersProgramRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiPublicInvestorInterestRoute: typeof ApiPublicInvestorInterestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tester': {
      id: '/tester'
      path: '/tester'
      fullPath: '/tester'
      preLoaderRoute: typeof TesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-solutions': {
      id: '/seller-solutions'
      path: '/seller-solutions'
      fullPath: '/seller-solutions'
      preLoaderRoute: typeof SellerSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-sellers': {
      id: '/for-sellers'
      path: '/for-sellers'
      fullPath: '/for-sellers'
      preLoaderRoute: typeof ForSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-buyers': {
      id: '/for-buyers'
      path: '/for-buyers'
      fullPath: '/for-buyers'
      preLoaderRoute: typeof ForBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards/': {
      id: '/gift-cards/'
      path: '/'
      fullPath: '/gift-cards/'
      preLoaderRoute: typeof GiftCardsIndexRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/news/market360-testers-program': {
      id: '/news/market360-testers-program'
      path: '/news/market360-testers-program'
      fullPath: '/news/market360-testers-program'
      preLoaderRoute: typeof NewsMarket360TestersProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/market360-gift-cards-launch': {
      id: '/news/market360-gift-cards-launch'
      path: '/news/market360-gift-cards-launch'
      fullPath: '/news/market360-gift-cards-launch'
      preLoaderRoute: typeof NewsMarket360GiftCardsLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/market360-gift-card-collection': {
      id: '/news/market360-gift-card-collection'
      path: '/news/market360-gift-card-collection'
      fullPath: '/news/market360-gift-card-collection'
      preLoaderRoute: typeof NewsMarket360GiftCardCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/market360-android-app-live': {
      id: '/news/market360-android-app-live'
      path: '/news/market360-android-app-live'
      fullPath: '/news/market360-android-app-live'
      preLoaderRoute: typeof NewsMarket360AndroidAppLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards/silver': {
      id: '/gift-cards/silver'
      path: '/silver'
      fullPath: '/gift-cards/silver'
      preLoaderRoute: typeof GiftCardsSilverRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/gift-cards/platinum': {
      id: '/gift-cards/platinum'
      path: '/platinum'
      fullPath: '/gift-cards/platinum'
      preLoaderRoute: typeof GiftCardsPlatinumRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/gift-cards/m360-super': {
      id: '/gift-cards/m360-super'
      path: '/m360-super'
      fullPath: '/gift-cards/m360-super'
      preLoaderRoute: typeof GiftCardsM360SuperRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/gift-cards/gold': {
      id: '/gift-cards/gold'
      path: '/gold'
      fullPath: '/gift-cards/gold'
      preLoaderRoute: typeof GiftCardsGoldRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/gift-cards/diamond': {
      id: '/gift-cards/diamond'
      path: '/diamond'
      fullPath: '/gift-cards/diamond'
      preLoaderRoute: typeof GiftCardsDiamondRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/gift-cards/bronze': {
      id: '/gift-cards/bronze'
      path: '/bronze'
      fullPath: '/gift-cards/bronze'
      preLoaderRoute: typeof GiftCardsBronzeRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/api/public/investor-interest': {
      id: '/api/public/investor-interest'
      path: '/api/public/investor-interest'
      fullPath: '/api/public/investor-interest'
      preLoaderRoute: typeof ApiPublicInvestorInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GiftCardsRouteChildren {
  GiftCardsBronzeRoute: typeof GiftCardsBronzeRoute
  GiftCardsDiamondRoute: typeof GiftCardsDiamondRoute
  GiftCardsGoldRoute: typeof GiftCardsGoldRoute
  GiftCardsM360SuperRoute: typeof GiftCardsM360SuperRoute
  GiftCardsPlatinumRoute: typeof GiftCardsPlatinumRoute
  GiftCardsSilverRoute: typeof GiftCardsSilverRoute
  GiftCardsIndexRoute: typeof GiftCardsIndexRoute
}

const GiftCardsRouteChildren: GiftCardsRouteChildren = {
  GiftCardsBronzeRoute: GiftCardsBronzeRoute,
  GiftCardsDiamondRoute: GiftCardsDiamondRoute,
  GiftCardsGoldRoute: GiftCardsGoldRoute,
  GiftCardsM360SuperRoute: GiftCardsM360SuperRoute,
  GiftCardsPlatinumRoute: GiftCardsPlatinumRoute,
  GiftCardsSilverRoute: GiftCardsSilverRoute,
  GiftCardsIndexRoute: GiftCardsIndexRoute,
}

const GiftCardsRouteWithChildren = GiftCardsRoute._addFileChildren(
  GiftCardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  ForBuyersRoute: ForBuyersRoute,
  ForSellersRoute: ForSellersRoute,
  GiftCardsRoute: GiftCardsRouteWithChildren,
  HelpRoute: HelpRoute,
  InvestmentsRoute: InvestmentsRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SellerSolutionsRoute: SellerSolutionsRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TesterRoute: TesterRoute,
  WalletRoute: WalletRoute,
  NewsMarket360AndroidAppLiveRoute: NewsMarket360AndroidAppLiveRoute,
  NewsMarket360GiftCardCollectionRoute: NewsMarket360GiftCardCollectionRoute,
  NewsMarket360GiftCardsLaunchRoute: NewsMarket360GiftCardsLaunchRoute,
  NewsMarket360TestersProgramRoute: NewsMarket360TestersProgramRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiPublicInvestorInterestRoute: ApiPublicInvestorInterestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
