/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TesterRouteImport } from './routes/tester'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SellerSolutionsRouteImport } from './routes/seller-solutions'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForSellersRouteImport } from './routes/for-sellers'
import { Route as ForBuyersRouteImport } from './routes/for-buyers'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsWallet2LaunchRouteImport } from './routes/news.wallet-2-launch'
import { Route as NewsTesterSpotlightsRouteImport } from './routes/news.tester-spotlights'
import { Route as NewsTesterProgramLaunchRouteImport } from './routes/news.tester-program-launch'
import { Route as NewsSmarterSearchRouteImport } from './routes/news.smarter-search'
import { Route as NewsSellerDashboardRefreshRouteImport } from './routes/news.seller-dashboard-refresh'
import { Route as NewsRoadmapQ3RouteImport } from './routes/news.roadmap-q3'
import { Route as NewsFraudProtectionUpdateRouteImport } from './routes/news.fraud-protection-update'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ApiPublicInvestorInterestRouteImport } from './routes/api/public/investor-interest'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TesterRoute = TesterRouteImport.update({
  id: '/tester',
  path: '/tester',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSolutionsRoute = SellerSolutionsRouteImport.update({
  id: '/seller-solutions',
  path: '/seller-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSellersRoute = ForSellersRouteImport.update({
  id: '/for-sellers',
  path: '/for-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBuyersRoute = ForBuyersRouteImport.update({
  id: '/for-buyers',
  path: '/for-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsWallet2LaunchRoute = NewsWallet2LaunchRouteImport.update({
  id: '/wallet-2-launch',
  path: '/wallet-2-launch',
  getParentRoute: () => NewsRoute,
} as any)
const NewsTesterSpotlightsRoute = NewsTesterSpotlightsRouteImport.update({
  id: '/tester-spotlights',
  path: '/tester-spotlights',
  getParentRoute: () => NewsRoute,
} as any)
const NewsTesterProgramLaunchRoute = NewsTesterProgramLaunchRouteImport.update({
  id: '/tester-program-launch',
  path: '/tester-program-launch',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSmarterSearchRoute = NewsSmarterSearchRouteImport.update({
  id: '/smarter-search',
  path: '/smarter-search',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSellerDashboardRefreshRoute =
  NewsSellerDashboardRefreshRouteImport.update({
    id: '/seller-dashboard-refresh',
    path: '/seller-dashboard-refresh',
    getParentRoute: () => NewsRoute,
  } as any)
const NewsRoadmapQ3Route = NewsRoadmapQ3RouteImport.update({
  id: '/roadmap-q3',
  path: '/roadmap-q3',
  getParentRoute: () => NewsRoute,
} as any)
const NewsFraudProtectionUpdateRoute =
  NewsFraudProtectionUpdateRouteImport.update({
    id: '/fraud-protection-update',
    path: '/fraud-protection-update',
    getParentRoute: () => NewsRoute,
  } as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ApiPublicInvestorInterestRoute =
  ApiPublicInvestorInterestRouteImport.update({
    id: '/api/public/investor-interest',
    path: '/api/public/investor-interest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/help': typeof HelpRoute
  '/investments': typeof InvestmentsRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/seller-solutions': typeof SellerSolutionsRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tester': typeof TesterRoute
  '/wallet': typeof WalletRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/fraud-protection-update': typeof NewsFraudProtectionUpdateRoute
  '/news/roadmap-q3': typeof NewsRoadmapQ3Route
  '/news/seller-dashboard-refresh': typeof NewsSellerDashboardRefreshRoute
  '/news/smarter-search': typeof NewsSmarterSearchRoute
  '/news/tester-program-launch': typeof NewsTesterProgramLaunchRoute
  '/news/tester-spotlights': typeof NewsTesterSpotlightsRoute
  '/news/wallet-2-launch': typeof NewsWallet2LaunchRoute
  '/api/public/investor-interest': typeof ApiPublicInvestorInterestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/help': typeof HelpRoute
  '/investments': typeof InvestmentsRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/seller-solutions': typeof SellerSolutionsRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tester': typeof TesterRoute
  '/wallet': typeof WalletRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/fraud-protection-update': typeof NewsFraudProtectionUpdateRoute
  '/news/roadmap-q3': typeof NewsRoadmapQ3Route
  '/news/seller-dashboard-refresh': typeof NewsSellerDashboardRefreshRoute
  '/news/smarter-search': typeof NewsSmarterSearchRoute
  '/news/tester-program-launch': typeof NewsTesterProgramLaunchRoute
  '/news/tester-spotlights': typeof NewsTesterSpotlightsRoute
  '/news/wallet-2-launch': typeof NewsWallet2LaunchRoute
  '/api/public/investor-interest': typeof ApiPublicInvestorInterestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-sellers': typeof ForSellersRoute
  '/help': typeof HelpRoute
  '/investments': typeof InvestmentsRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/seller-solutions': typeof SellerSolutionsRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tester': typeof TesterRoute
  '/wallet': typeof WalletRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/fraud-protection-update': typeof NewsFraudProtectionUpdateRoute
  '/news/roadmap-q3': typeof NewsRoadmapQ3Route
  '/news/seller-dashboard-refresh': typeof NewsSellerDashboardRefreshRoute
  '/news/smarter-search': typeof NewsSmarterSearchRoute
  '/news/tester-program-launch': typeof NewsTesterProgramLaunchRoute
  '/news/tester-spotlights': typeof NewsTesterSpotlightsRoute
  '/news/wallet-2-launch': typeof NewsWallet2LaunchRoute
  '/api/public/investor-interest': typeof ApiPublicInvestorInterestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-buyers'
    | '/for-sellers'
    | '/help'
    | '/investments'
    | '/news'
    | '/privacy'
    | '/safety'
    | '/seller-solutions'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tester'
    | '/wallet'
    | '/news/$slug'
    | '/news/fraud-protection-update'
    | '/news/roadmap-q3'
    | '/news/seller-dashboard-refresh'
    | '/news/smarter-search'
    | '/news/tester-program-launch'
    | '/news/tester-spotlights'
    | '/news/wallet-2-launch'
    | '/api/public/investor-interest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-buyers'
    | '/for-sellers'
    | '/help'
    | '/investments'
    | '/news'
    | '/privacy'
    | '/safety'
    | '/seller-solutions'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tester'
    | '/wallet'
    | '/news/$slug'
    | '/news/fraud-protection-update'
    | '/news/roadmap-q3'
    | '/news/seller-dashboard-refresh'
    | '/news/smarter-search'
    | '/news/tester-program-launch'
    | '/news/tester-spotlights'
    | '/news/wallet-2-launch'
    | '/api/public/investor-interest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-buyers'
    | '/for-sellers'
    | '/help'
    | '/investments'
    | '/news'
    | '/privacy'
    | '/safety'
    | '/seller-solutions'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tester'
    | '/wallet'
    | '/news/$slug'
    | '/news/fraud-protection-update'
    | '/news/roadmap-q3'
    | '/news/seller-dashboard-refresh'
    | '/news/smarter-search'
    | '/news/tester-program-launch'
    | '/news/tester-spotlights'
    | '/news/wallet-2-launch'
    | '/api/public/investor-interest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  ForBuyersRoute: typeof ForBuyersRoute
  ForSellersRoute: typeof ForSellersRoute
  HelpRoute: typeof HelpRoute
  InvestmentsRoute: typeof InvestmentsRoute
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SellerSolutionsRoute: typeof SellerSolutionsRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TesterRoute: typeof TesterRoute
  WalletRoute: typeof WalletRoute
  ApiPublicInvestorInterestRoute: typeof ApiPublicInvestorInterestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tester': {
      id: '/tester'
      path: '/tester'
      fullPath: '/tester'
      preLoaderRoute: typeof TesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-solutions': {
      id: '/seller-solutions'
      path: '/seller-solutions'
      fullPath: '/seller-solutions'
      preLoaderRoute: typeof SellerSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-sellers': {
      id: '/for-sellers'
      path: '/for-sellers'
      fullPath: '/for-sellers'
      preLoaderRoute: typeof ForSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-buyers': {
      id: '/for-buyers'
      path: '/for-buyers'
      fullPath: '/for-buyers'
      preLoaderRoute: typeof ForBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/wallet-2-launch': {
      id: '/news/wallet-2-launch'
      path: '/wallet-2-launch'
      fullPath: '/news/wallet-2-launch'
      preLoaderRoute: typeof NewsWallet2LaunchRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/tester-spotlights': {
      id: '/news/tester-spotlights'
      path: '/tester-spotlights'
      fullPath: '/news/tester-spotlights'
      preLoaderRoute: typeof NewsTesterSpotlightsRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/tester-program-launch': {
      id: '/news/tester-program-launch'
      path: '/tester-program-launch'
      fullPath: '/news/tester-program-launch'
      preLoaderRoute: typeof NewsTesterProgramLaunchRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/smarter-search': {
      id: '/news/smarter-search'
      path: '/smarter-search'
      fullPath: '/news/smarter-search'
      preLoaderRoute: typeof NewsSmarterSearchRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/seller-dashboard-refresh': {
      id: '/news/seller-dashboard-refresh'
      path: '/seller-dashboard-refresh'
      fullPath: '/news/seller-dashboard-refresh'
      preLoaderRoute: typeof NewsSellerDashboardRefreshRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/roadmap-q3': {
      id: '/news/roadmap-q3'
      path: '/roadmap-q3'
      fullPath: '/news/roadmap-q3'
      preLoaderRoute: typeof NewsRoadmapQ3RouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/fraud-protection-update': {
      id: '/news/fraud-protection-update'
      path: '/fraud-protection-update'
      fullPath: '/news/fraud-protection-update'
      preLoaderRoute: typeof NewsFraudProtectionUpdateRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/api/public/investor-interest': {
      id: '/api/public/investor-interest'
      path: '/api/public/investor-interest'
      fullPath: '/api/public/investor-interest'
      preLoaderRoute: typeof ApiPublicInvestorInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsFraudProtectionUpdateRoute: typeof NewsFraudProtectionUpdateRoute
  NewsRoadmapQ3Route: typeof NewsRoadmapQ3Route
  NewsSellerDashboardRefreshRoute: typeof NewsSellerDashboardRefreshRoute
  NewsSmarterSearchRoute: typeof NewsSmarterSearchRoute
  NewsTesterProgramLaunchRoute: typeof NewsTesterProgramLaunchRoute
  NewsTesterSpotlightsRoute: typeof NewsTesterSpotlightsRoute
  NewsWallet2LaunchRoute: typeof NewsWallet2LaunchRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsFraudProtectionUpdateRoute: NewsFraudProtectionUpdateRoute,
  NewsRoadmapQ3Route: NewsRoadmapQ3Route,
  NewsSellerDashboardRefreshRoute: NewsSellerDashboardRefreshRoute,
  NewsSmarterSearchRoute: NewsSmarterSearchRoute,
  NewsTesterProgramLaunchRoute: NewsTesterProgramLaunchRoute,
  NewsTesterSpotlightsRoute: NewsTesterSpotlightsRoute,
  NewsWallet2LaunchRoute: NewsWallet2LaunchRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  ForBuyersRoute: ForBuyersRoute,
  ForSellersRoute: ForSellersRoute,
  HelpRoute: HelpRoute,
  InvestmentsRoute: InvestmentsRoute,
  NewsRoute: NewsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SellerSolutionsRoute: SellerSolutionsRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TesterRoute: TesterRoute,
  WalletRoute: WalletRoute,
  ApiPublicInvestorInterestRoute: ApiPublicInvestorInterestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
